### PR TITLE
Issue 345

### LINKED ISSUE #345: 'MATLAB Build Results' links from 2.1.3.1 throws a warning in the system log
When trying to access the Build results which are generated in 2.13.1, throws a warning.

Repro steps:
1. Install 2.13.1 version and generate a Build result table
2. Update the plugin to new changes from dev_main

Anomalies with accessing the 'MATLAB Build Results':

When clicked on 'MATLAB Build Results' :
image
It shows how many tasks are run but not the tasks information:
image

Clicking on 'MATLAB Build Results'  also throws a warning in Jenkins System log:
image

When clicked on the 'MATLAB Build Results' from build Status page, no table is shown
image

What is the expected behavior with build results form previous version?

### PR DESCRIPTION
**Pull request by nbhoski**
This PR closes #345 
* Maintains the backward compatibility for reading build artifact

### CODE REVIEW

File: src/main/java/com/mathworks/ci/BuildArtifactAction.java [hunk 1]
```diff
@@ -61,14 +61,19 @@ public String getDisplayName() {
     @CheckForNull
     @Override
     public String getUrlName() {
-        return "buildresults" + this.actionID ;
+        return (this.actionID == null) ? "buildresults" : "buildresults" + this.actionID ;
```
Comment (mw-kapilg) [inline src/main/java/com/mathworks/ci/BuildArtifactAction.java:64]:
```suggestion
        return "buildresults" + (this.actionID == null ? "" : this.actionID);
```

File: src/main/java/com/mathworks/ci/BuildArtifactAction.java
Comment (mw-kapilg) [inline src/main/java/com/mathworks/ci/BuildArtifactAction.java:1]: Should we just initialize the class variable `actionsID` as empty string like `private String actionID = "";` (line 27)? That way we'd able to avoid all the null checking here

**Review by mw-kapilg — APPROVED** [review]

File: src/main/java/com/mathworks/ci/BuildArtifactAction.java
Comment (nbhoski) [reply src/main/java/com/mathworks/ci/BuildArtifactAction.java:1]: hmm, We would still need to check for ""

File: src/main/java/com/mathworks/ci/BuildArtifactAction.java (hunk 1 above)
Comment (nbhoski) [reply src/main/java/com/mathworks/ci/BuildArtifactAction.java:64]: why to send buildresults+"" ?

**Comment by nbhoski** [comment]
Thanks @mw-kapilg

File: src/main/java/com/mathworks/ci/BuildArtifactAction.java
Comment (mw-kapilg) [reply src/main/java/com/mathworks/ci/BuildArtifactAction.java:1]: We could use the `actionID` variable directly right?

File: src/main/java/com/mathworks/ci/BuildArtifactAction.java (hunk 1 above)
Comment (mw-kapilg) [reply src/main/java/com/mathworks/ci/BuildArtifactAction.java:64]: The suggested change is to avoid using the string literal `"buildresults"` twice
