### PR TITLE
Fixed issue 338

### LINKED ISSUE #338: Build results table getting overwritten
When I run two builds in a project the second build results table is overwriting the first. There are two links, and two summaries on the status page, but it is linking to the same table.

### PR DESCRIPTION
**Pull request by nbhoski**
This PR Closes #338 
#### Changes include 
* Added `actionID` to identify each build task separately.
* Under Jenkins root folder now files are getting store with `actionID` postfixed to it eg `buildArtifact<actionID>.jason` 
* `TaskRunProgressPlugin.m` now attaches `actionID` to the each task to avoid conflicting links.

#### Screenshots 
image

***
image

***
image

***
image

***

**Note: There are a few open questions here about the summary page where we can see multiple summaries as shown below. Please let me know your thoughts on the same if we need to continue as shown below. combining the summary has some UI 
limitations from Jenkins side.**  

image

* **We are adding `actionID` in the logf sentinals to avoid conflicting hyperlinks in case both build runs the same tasks. Should we support this ? per me its very rare that under same job somebody would run the same tasks.** 

image

### CODE REVIEW

File: src/main/java/com/mathworks/ci/BuildArtifactAction.java [hunk 1]
```diff
@@ -40,6 +42,9 @@ public BuildArtifactAction(Run<?, ?> build) {
         }
     }
 
+    public String getActionID(){
+        return this.actionID;
+    }
```
Comment (sameagen-MW) [inline src/main/java/com/mathworks/ci/BuildArtifactAction.java:47]: New line after this for consistent white space?

File: src/main/java/com/mathworks/ci/BuildArtifactAction.java [hunk 2]
```diff
@@ -55,12 +60,13 @@ public String getDisplayName() {
...
     public String getUrlName() {
-        return "buildresults";
+        return "buildresults" + this.actionID ;
     }
 
     public List<BuildArtifactData> getBuildArtifact() throws ParseException, InterruptedException, IOException {
         List<BuildArtifactData> artifactData = new ArrayList<BuildArtifactData>();
-        FilePath fl = new FilePath(new File(build.getRootDir().getAbsolutePath(), BUILD_ARTIFACT_FILE));
+
+        FilePath fl = new FilePath(new File(build.getRootDir().getAbsolutePath() + "/" + BUILD_ARTIFACT_FILE + this.actionID +".json"));
```
Comment (sameagen-MW) [inline src/main/java/com/mathworks/ci/BuildArtifactAction.java:69]:
```suggestion
        FilePath fl = new FilePath(new File(build.getRootDir().getAbsolutePath() + "/" + BUILD_ARTIFACT_FILE + this.actionID + ".json"));
```

File: src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java [hunk 3]
```diff
@@ -29,6 +29,15 @@ public class RunMatlabBuildAction {
         "+ciplugins/+jenkins/BuildReportPlugin.m";
     private static String TASK_RUN_PROGRESS_PLUGIN = 
         "+ciplugins/+jenkins/TaskRunProgressPlugin.m";
+    private String actionID;
+
+    public String getActionID(){
+        return this.actionID;
+    }
```
Comment (sameagen-MW) [inline src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java:36]: `actionID` seems like implementation detail here rather than part of the class's interface that we want to expose. I think my preference is to remove the setter and getter and just set the value in the constructor as currently they're adding verbosity without much benefit.

File: src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java [hunk 4]
```diff
@@ -29,6 +29,15 @@ public class RunMatlabBuildAction {
...
+
+    private void setActionID(){
+        this.actionID = RandomStringUtils.randomAlphanumeric(8);
+    }
 
     public RunMatlabBuildAction(MatlabCommandRunner runner, BuildConsoleAnnotator annotator, BuildActionParameters params) {
         this.runner = runner;
```
Comment (sameagen-MW) [inline src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java:43]:
```suggestion
        this.runner = runner;
        this.actionID = RandomStringUtils.randomAlphanumeric(8);
```

File: src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java (hunk 3 above)
Comment (sameagen-MW) [inline src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java:36]:
```suggestion
```

File: src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java [hunk 5]
```diff
@@ -29,6 +29,15 @@ public class RunMatlabBuildAction {
...
         "+ciplugins/+jenkins/TaskRunProgressPlugin.m";
+    private String actionID;
+
+    public String getActionID(){
+        return this.actionID;
+    }
+
+    private void setActionID(){
+        this.actionID = RandomStringUtils.randomAlphanumeric(8);
+    }
```
Comment (sameagen-MW) [inline src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java:40]:
```suggestion
```

File: src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java [hunk 6]
```diff
@@ -45,15 +54,19 @@ public RunMatlabBuildAction(BuildActionParameters params) throws IOException, In
     }
 
     public void run() throws IOException, InterruptedException, MatlabExecutionException {
+        // set unique action ID for each build task
+        this.setActionID();
```
Comment (sameagen-MW) [inline src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java:58]:
```suggestion
```

File: src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java [hunk 7]
```diff
@@ -93,11 +106,11 @@ public void run() throws IOException, InterruptedException, MatlabExecutionExcep
                     FilePath rootLocation = new FilePath(
                             new File(
                                 build.getRootDir().getAbsolutePath(),
-                                "buildArtifact.json")
+                                "buildArtifact" + this.getActionID() + ".json")
```
Comment (sameagen-MW) [inline src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java:109]:
```suggestion
                                "buildArtifact" + this.actionID + ".json")
```

File: src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java [hunk 8]
```diff
@@ -93,11 +106,11 @@ public void run() throws IOException, InterruptedException, MatlabExecutionExcep
...
                             );
                     jsonFile.copyTo(rootLocation);
                     jsonFile.delete();
-                    build.addAction(new BuildArtifactAction(build));
+                    build.addAction(new BuildArtifactAction(build, this.getActionID()));
```
Comment (sameagen-MW) [inline src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java:113]:
```suggestion
                    build.addAction(new BuildArtifactAction(build, this.actionID));
```

File: src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java [hunk 9]
```diff
@@ -111,5 +124,6 @@ public void run() throws IOException, InterruptedException, MatlabExecutionExcep
                 }
             }
         }
+
```
Comment (sameagen-MW) [inline src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java:127]:
```suggestion
```

File: src/test/java/integ/com/mathworks/ci/BuildArtifactActionTest.java [hunk 10]
```diff
@@ -71,9 +71,11 @@ private URL getResource(String resource) {
...
-        BuildArtifactAction ac = new BuildArtifactAction(build);
+        final String actionID = "abc123";
+        final String targetFile = "buildArtifact"+ actionID + ".json";
+        BuildArtifactAction ac = new BuildArtifactAction(build, actionID);
         FilePath artifactRoot = new FilePath(build.getRootDir());
-        copyFileInWorkspace("buildArtifacts/t1/buildArtifact.json","buildArtifact.json",artifactRoot);
+        copyFileInWorkspace("buildArtifacts/t1/buildArtifact.json",targetFile,artifactRoot);
         List<BuildArtifactData> ba = ac.getBuildArtifact();
         int expectedSize = ba.size();
         Assert.assertEquals("The build names are not matching",3,expectedSize);
```
Comment (sameagen-MW) [inline src/test/java/integ/com/mathworks/ci/BuildArtifactActionTest.java:81]: Update assertion message?

File: src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java [hunk 11]
```diff
@@ -45,15 +54,19 @@ public RunMatlabBuildAction(BuildActionParameters params) throws IOException, In
...
         runner.copyFileToTempFolder(DEFAULT_PLUGIN, DEFAULT_PLUGIN);
         runner.copyFileToTempFolder(BUILD_REPORT_PLUGIN, BUILD_REPORT_PLUGIN);
         runner.copyFileToTempFolder(TASK_RUN_PROGRESS_PLUGIN, TASK_RUN_PROGRESS_PLUGIN);
+
         
         // Set environment variable
         runner.addEnvironmentVariable(
                 "MW_MATLAB_BUILDTOOL_DEFAULT_PLUGINS_FCN_OVERRIDE",
                 "ciplugins.jenkins.getDefaultPlugins");
+        runner.addEnvironmentVariable("MW_BUILD_PLUGIN_ACTION_ID",this.getActionID());
```
Comment (sameagen-MW) [inline src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java:69]:
```suggestion
        runner.addEnvironmentVariable("MW_BUILD_PLUGIN_ACTION_ID",this.actionID);
```

**Review by sameagen-MW — APPROVED** [review]

File: src/main/java/com/mathworks/ci/BuildArtifactAction.java (hunk 1 above)
Comment (nbhoski) [reply src/main/java/com/mathworks/ci/BuildArtifactAction.java:47]: Done.

File: src/main/java/com/mathworks/ci/BuildArtifactAction.java (hunk 2 above)
Comment (nbhoski) [reply src/main/java/com/mathworks/ci/BuildArtifactAction.java:69]: Done.

File: src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java (hunk 4 above)
Comment (nbhoski) [reply src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java:43]: Done.

File: src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java (hunk 3 above)
Comment (nbhoski) [reply src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java:36]: I think getter is needed for tests as well as to access the action ID. I am inclined to keep the getter

File: src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java (hunk 5 above)
Comment (nbhoski) [reply src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java:40]: Done.

File: src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java (hunk 6 above)
Comment (nbhoski) [reply src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java:58]: Done.

File: src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java (hunk 7 above)
Comment (nbhoski) [reply src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java:109]: keeping getters

File: src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java (hunk 8 above)
Comment (nbhoski) [reply src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java:113]: Same as above.

File: src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java (hunk 9 above)
Comment (nbhoski) [reply src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java:127]: Done.

File: src/test/java/integ/com/mathworks/ci/BuildArtifactActionTest.java (hunk 10 above)
Comment (nbhoski) [reply src/test/java/integ/com/mathworks/ci/BuildArtifactActionTest.java:81]: Done.

File: src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java (hunk 11 above)
Comment (nbhoski) [reply src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java:69]: getters are intact.

File: src/main/java/com/mathworks/ci/BuildArtifactAction.java [hunk 12]
```diff
@@ -24,11 +24,13 @@ public class BuildArtifactAction implements Action {
     private int totalCount;
     private int skipCount;
     private int failCount;
+    private String actionID;
     private static final String ROOT_ELEMENT = "taskDetails";
-    private static final String BUILD_ARTIFACT_FILE = "buildArtifact.json";
+    private static final String BUILD_ARTIFACT_FILE = "buildArtifact";
```
[the remark this answers is not in the document]
Comment (nbhoski) [reply src/main/java/com/mathworks/ci/BuildArtifactAction.java:29]: how about matlabBuildReport ?

[the remark this answers is not in the document]
Comment (nbhoski) [reply src/main/java/com/mathworks/ci/BuildArtifactAction.java:29]: UUID is 128 bit long i wanted to avoid any extra logic to cut it down in 8 bit.

File: src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java (hunk 3 above)
Comment (sameagen-MW) [reply src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java:36]: Sounds good to me!

File: src/main/java/com/mathworks/ci/BuildArtifactAction.java [hunk 13]
```diff
@@ -55,12 +61,14 @@ public String getDisplayName() {
...
-        return "buildresults";
+        return "buildresults" + this.actionID ;
     }
 
     public List<BuildArtifactData> getBuildArtifact() throws ParseException, InterruptedException, IOException {
         List<BuildArtifactData> artifactData = new ArrayList<BuildArtifactData>();
-        FilePath fl = new FilePath(new File(build.getRootDir().getAbsolutePath(), BUILD_ARTIFACT_FILE));
+
+        FilePath fl = new FilePath(new File(build.getRootDir().getAbsolutePath() + "/" +
+                BUILD_ARTIFACT_FILE + this.actionID + ".json"));
```
Comment (sameagen-MW) [inline src/main/java/com/mathworks/ci/BuildArtifactAction.java:71]:
```suggestion
        FilePath fl = new FilePath(new File(
                build.getRootDir().getAbsolutePath(),
                BUILD_ARTIFACT_FILE + this.actionID + ".json"
        ));
```

File: src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java [hunk 14]
```diff
@@ -49,11 +55,13 @@ public void run() throws IOException, InterruptedException, MatlabExecutionExcep
         runner.copyFileToTempFolder(DEFAULT_PLUGIN, DEFAULT_PLUGIN);
         runner.copyFileToTempFolder(BUILD_REPORT_PLUGIN, BUILD_REPORT_PLUGIN);
         runner.copyFileToTempFolder(TASK_RUN_PROGRESS_PLUGIN, TASK_RUN_PROGRESS_PLUGIN);
+
```
Comment (sameagen-MW) [inline src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java:58]:
```suggestion
```

File: src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java [hunk 15]
```diff
@@ -111,5 +119,6 @@ public void run() throws IOException, InterruptedException, MatlabExecutionExcep
                 }
             }
         }
+
```
Comment (sameagen-MW) [inline src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java:122]:
```suggestion
```

**Review by sameagen-MW — APPROVED** [review]

File: src/main/java/com/mathworks/ci/BuildArtifactAction.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (mcafaro) [reply src/main/java/com/mathworks/ci/BuildArtifactAction.java:29]: "matlabBuildReport" or "runMatlabBuildReport" or "buildReport" all seem reasonable. Seems like this class name should potentially be reconsidered as well. Perhaps "BuildReportAction" or "RunMatlabBuildReportAction" or something like that.

**Review by mcafaro — APPROVED** [review]
Future note: try to keep the reviewer list to a single dev reviewer (outside of Houman for user facing messages).
